"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Locale = "en" | "es" | "zh";

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

// Translations Dictionary for Core UI
export const translations: Record<Locale, Record<string, string>> = {
  en: {
    // Navbar
    home: "HOME",
    markets: "MARKETS",
    ai_agents: "AI AGENTS",
    swarm_ai: "SWARM AI",
    portfolio: "PORTFOLIO",
    governance: "GOVERNANCE",
    launch_terminal: "LAUNCH TERMINAL",
    footer_tx: "LATEST TX",

    // Hero
    hero_headline: "INSTITUTIONAL AI. ON-CHAIN PREDICTIONS.",
    hero_subtitle: "Multi-LLM Swarm (DeepSeek R1 → Claude 3.5 → OpenAI o1) + Non-Custodial NeuralVaults + MPP Payment Protocol (x402). Zero hallucination. Full on-chain audit trail.",
    hero_cta1: "INITIALIZE TERMINAL",
    hero_cta2: "SWARM COMMAND CENTER",

    // Workflow
    workflow_title: "PROTOCOL WORKFLOW",
    workflow_subtitle: "From connection to execution, Neural Market operates on a trustless, automated infrastructure.",
    step1_title: "CONNECT IDENTITY",
    step1_desc: "Link your Solana wallet to establish your verifiable on-chain identity within the Neural Network.",
    step2_title: "ACTIVATE SWARM",
    step2_desc: "Deploy autonomous AI agents (Whale Watcher, Sniper, Sentiment) to analyze Kalshi markets 24/7.",
    step3_title: "EXECUTE & EARN",
    step3_desc: "Agents execute trades instantly via DFlow. Follow your PnL and climb the global leaderboard.",
    step4_title: "GOVERNANCE",
    step4_desc: "Stake your earnings to gain voting power in the Neural Council and propose new markets.",

    // Bento Grid
    arch_title: "SYSTEM ARCHITECTURE",
    bento1_title: "Neural Swarm Intelligence",
    bento1_desc: "Decentralized network of specialized AI agents running on ElizaOS. Powered by DeepSeek R1 for local privacy.",
    bento2_title: "Instant Execution",
    bento2_desc: "Powered by Solana's high-throughput blockchain.",
    bento3_title: "Kalshi Integration",
    bento3_desc: "Direct feed from Kalshi, the first CFTC-regulated exchange for event contracts.",
    bento4_title: "DFlow Liquidity",
    bento4_desc: "Aggregated liquidity via DFlow ensuring minimal slippage through advanced order routing.",
    bento5_title: "NeuralVault",
    bento1_desc_v2: "Anchor-based Solana USDC vault. Set risk limits on-chain. 0.5% protocol fee auto-collected.",
    bento6_title: "Jupiter Integration",
    bento6_desc: "Seamlessly swap between SOL, USDC, or BONK directly within the execution interface.",
    mpp_title: "MPP X402 GATEWAY",
    mpp_desc: "Machine-to-Machine API monetization. Every prediction call is enforced via HTTP 402 for 0.05 USDC.",
    multi_llm_title: "MULTI-LLM ORCHESTRATOR",
    multi_llm_desc: "DeepSeek R1 (local) → Claude 3.5 Sonnet (structured) → OpenAI o1 (risk validation).",

    // Agents Creation
    agent_genesis: "AGENT GENESIS PROTOCOL",
    select_archetype: "SELECT ARCHETYPE",
    archetype_desc: "Choose the neural personality core. This defines the agent's base trading philosophy.",
    sniper_title: "THE SNIPER",
    sniper_desc: "High frequency. Executes on micro-divergences.",
    oracle_title: "THE ORACLE",
    oracle_desc: "Sentiment analysis. Scrapes X & News API.",
    hedger_title: "THE HEDGER",
    hedger_desc: "Delta-neutral. Harvests executor rewards.",
    whale_title: "WHALE TRACKER",
    whale_desc: "Follows large wallet movements. Copies smart money.",
    next_phase: "NEXT PHASE",
    back: "BACK",
    system_calibration: "SYSTEM CALIBRATION",
    calibration_desc: "Configure risk parameters and capital allocation. Higher leverage increases volatility exposure.",
    risk_tolerance: "RISK TOLERANCE",
    capital: "CAPITAL",
    leverage: "LEVERAGE",
    safe: "SAFE",
    yolo: "YOLO",
    degen: "DEGEN",
    aggressive: "AGGRESSIVE",
    conservative: "CONSERVATIVE",

    // Footer
    footer_desc: "Neural Market protocol provides institutional-grade event liquidity. Powered by Direct Kalshi API Feed and secured via distributed MPC and CCP orchestration for autonomous AI agent swarms.",
    footer_platform: "PLATFORM",
    footer_support: "SUPPORT",
    footer_legal: "LEGAL",
    footer_help: "Help Center",
    footer_faq: "FAQ",
    footer_contact: "Contact Us",
    footer_terms: "Terms of Service",
    footer_privacy: "Privacy Policy",
    footer_risk: "Risk Disclosure",
    footer_audit: "Security Audit",
    footer_status: "SYSTEM STATUS",
    footer_contract: "CONTRACT",

    // Markets
    markets_title: "INSTITUTIONAL LIQUIDITY",
    markets_subtitle: "Access real-time institutional event contracts powered by the Kalshi API. Validated by a 3-Tier Multi-LLM Swarm with full on-chain execution via NeuralVaults.",
    markets_stat_active: "Active Markets",
    markets_stat_vol: "24h Volume",
    markets_stat_new: "New Requests",
    markets_propose: "Propose New Market",
    search_placeholder: "SEARCH BY TICKER OR EVENT...",
    sort_by: "Sort By",
    sort_vol: "HIGHEST VOLUME",
    sort_new: "NEWEST LISTED",
    reveal_more: "REVEAL MORE",
    analyzing: "ANALYZING...",
    no_matches: "No matches found for your current filters.",
    clear_filters: "CLEAR ALL FILTERS",
    cat_all: "ALL",
    cat_crypto: "CRYPTO",
    cat_eco: "ECONOMICS",
    cat_pol: "POLITICS",
    cat_sci: "SCIENCE",
    cat_cul: "CULTURE",
    yes: "YES",
    no: "NO",
    price: "PRICE",
    trade: "TRADE",

    // Leaderboard
    leaderboard_title: "AI AGENTS",
    leaderboard_subtitle: "Top-performing autonomous agents on the neural network. Ranked by ELO Rating and validated via 3-Tier Cognitive Consensus.",
    total_agents: "Total Agents",
    total_tvl: "Total Volume (TVL)",
    search_agents: "Search agents by name or ID...",
    syncing: "SYNCING WITH SOLANA BLOCKCHAIN...",
    no_agents: "NO AGENTS FOUND",
    adjust_filters: "Try adjusting your filters",
    rank: "RANK",
    score: "SCORE",
    leaderboard_header: "AGENT LEADERBOARD",
    leaderboard_desc: "Top Performing Neural Agents (All Users)",
    scanning: "SCANNING BLOCKCHAIN FOR TOP AGENTS...",
    no_trades: "NO AGENTS WITH TRADES FOUND YET",
    trades: "TRADES",
    win_rate: "WIN RATE",
    total_pnl: "TOTAL PNL",
    showing_top: "Showing top 10 of",
    agents_count: "agents",
    view_details: "VIEW DETAILS",
    active: "ACTIVE",
    verified: "VERIFIED",
    lifetime_earnings: "Lifetime Earnings",
    managed_assets: "Managed Assets",
    total_executions: "Total Executions",
    neural_strategy: "NEURAL STRATEGY",
    recent_activity: "RECENT ACTIVITY",
    neural: "NEURAL",
    simulation_deploy: "SIMULATION & DEPLOY",
    simulation_desc: "Review historical performance based on selected parameters. Results may vary in live markets.",
    protocol_license_fee: "Protocol License Fee",
    deploy_legal_notice: "By clicking Deploy, you confirm this is a non-refundable software license fee for utilizing the NeuralVault infrastructure. Gas fees (~0.000005 SOL) are separate.",
    pay_and_deploy: "PAY 0.05 SOL & DEPLOY",
    initiating_genesis: "INITIATING GENESIS",
    initializing_neural_link: "INITIALIZING NEURAL LINK...",
    deploying_agent_status: "DEPLOYING AGENT...",
    required_fee_status: "REQUIRED: 0.05 SOL PROTOCOL FEE",
    requesting_signature_status: "REQUESTING WALLET SIGNATURE...",
    waiting_confirmation_status: "WAITING FOR CONFIRMATION...",
    deployed_successfully_status: "AGENT DEPLOYED SUCCESSFULLY ✓",
    connect_wallet_deploy: "PLEASE CONNECT WALLET TO DEPLOY AGENT",
    transaction_cancelled: "TRANSACTION CANCELLED BY USER",
    deployment_failed: "DEPLOYMENT FAILED",
    view_explorer: "VIEW ON EXPLORER",
    confirm_deactivate: "Are you sure you want to deactivate {name}?",
    connect_wallet_action: "Please connect your wallet first!",
    the_agora: "THE AGORA",
    agora_desc: "Stake-weighted governance facilitated by the {council}. Top-voted proposals are automatically submitted to Kalshi/DFlow for listing via decentralized pipelines.",
    neural_council: "Neural Council",
    connect_wallet_vote: "Connect wallet to vote on proposals",
    request_market: "REQUEST NEW MARKET",
    total_proposals: "TOTAL PROPOSALS",
    votes_cast_total: "VOTES CAST (TOTAL)",
    top_proposal_votes: "TOP PROPOSAL VOTES",
    filter_all: "ALL",
    filter_trending: "TRENDING",
    filter_new: "NEW",
    filter_ending: "ENDING SOON",
    loading_proposals: "LOADING PROPOSALS...",
    council_access_only: "COUNCIL ACCESS ONLY",
    council_denied_desc: "Submitting new governance proposals requires a Neural Council Membership NFT and active reputation stake. Please go to DAO Dashboard to qualify.",
    by_author: "by",
    threshold: "Threshold",
    voted: "VOTED",
    vote_action: "VOTE",
    voting: "VOTING...",
    vote_failed: "Vote failed",
    acknowledge: "ACKNOWLEDGE",
    copy_trade: "COPY TRADE (SOON)",
    view_solana: "VIEW ON SOLANA",
    strategy_desc_sniper: "utilizes a SNIPER strategy, focusing on high-frequency entries and quick exits based on DFlow order flow imbalances.",
    strategy_desc_whale: "utilizes a WHALE strategy, focusing on long-term accumulation and large-scale trend following using on-chain volume analysis.",
    strategy_desc_default: "utilizes a balanced strategy, focusing on risk management and probability-weighted entries across major prediction markets.",

    // Cortex System
    swarm_intel: "SWARM INTELLIGENCE",
    swarm_desc: "Autonomous Swarm Management System v5.0",
    activate_swarm: "ACTIVATE SWARM",
    deactivate_swarm: "DEACTIVATE SWARM",
    deploy_agent: "DEPLOY NEW AGENT",
    live_balance: "LIVE WALLET BALANCE (DEVNET)",
    connecting: "CONNECTING...",
    scanning_addr: "SCANNING ADDRESS...",
    vault_performance: "VAULT PERFORMANCE (ON-CHAIN)",
    accuracy: "ACCURACY",
    verified_predictions: "VERIFIED PREDICTIONS",
    based_on: "BASED ON",
    my_agents: "MY DEPLOYED AGENTS",
    manage_swarms: "Manage your active autonomous swarms on Solana Devnet",
    no_agents_deployed: "NO AGENTS DEPLOYED YET",
    create_first: "CREATE YOUR FIRST AGENT",
    fetching_logs: "FETCHING ON-CHAIN LOGS...",
    no_recent_activity: "NO RECENT ACTIVITY FOUND",
    recent_onchain: "RECENT ON-CHAIN ACTIVITY",
    execute_trade: "Execute Trade",
    manage_liquidity: "Manage Liquidity",
    stop_agent: "Stop Agent",
    reactivating: "Reactivating agent...",
    deactivating: "Deactivating agent...",
    agent_deactivated: "Agent deactivated!",
    agent_reactivated: "Agent reactivated!",
    view_tx: "View Transaction",
    trade_action: "TRADE",
    deposit: "DEPOSIT",
    reactivate: "REACTIVATE AGENT",
    risk: "RISK",
    leverage_short: "LEV",
    performance: "PERFORMANCE",
    error: "ERROR",
    active_nodes: "ACTIVE NODES (SWARM)",
    status: "STATUS",
    executing: "EXECUTING",
    connecting_hive: "CONNECTING TO HIVE...",
    conf: "CONF",
    neural_core: "NEURAL CORE",
    processing: "PROCESSING",
    network_status: "NETWORK STATUS",
    devnet_live: "DEVNET LIVE",
    offline: "OFFLINE",
    agent_balance_sol: "AGENT BALANCE (USDC)",
    vault_volume: "VAULT VOLUME",
    predictions: "PREDICTIONS",
    live: "LIVE",
    system_initializing: "SYSTEM INITIALIZING...",
    waiting_feed: "WAITING FOR NEURAL FEED...",
    global_feed: "Global Sync Feed",
    realtime_logs: "Real-time On-Chain Transaction Logs (Devnet)",
    signature: "Signature",
    slot: "Slot",
    time: "Time",
    view: "View",
    failed: "FAILED",
    confirmed: "CONFIRMED",
    no_activity: "No on-chain activity detected yet",
  },
  es: {
    // Navbar
    home: "INICIO",
    markets: "MERCADOS",
    ai_agents: "AGENTES IA",
    swarm_ai: "SWARM IA",
    portfolio: "PORTAFOLIO",
    governance: "GOBERNANZA",
    launch_terminal: "ABRIR TERMINAL",
    footer_tx: "ÚLTIMA TX",

    // Hero
    hero_headline: "IA INSTITUCIONAL. PREDICCIONES ON-CHAIN.",
    hero_subtitle: "Multi-LLM Swarm (DeepSeek R1 → Claude 3.5 → OpenAI o1) + NeuralVaults No-Custodios + Protocolo de Pagos MPP (x402). Sin alucinaciones. Auditoría total on-chain.",
    hero_cta1: "INICIALIZAR TERMINAL",
    hero_cta2: "CENTRO DE MANDO SWARM",

    // Workflow
    workflow_title: "FLUJO DEL PROTOCOLO",
    workflow_subtitle: "Desde la conexión hasta la ejecución, Neural Market opera sobre una infraestructura automatizada y sin confianza.",
    step1_title: "CONECTAR IDENTIDAD",
    step1_desc: "Vincula tu wallet de Solana para establecer tu identidad on-chain verificable dentro de la Red Neural.",
    step2_title: "ACTIVAR SWARM",
    step2_desc: "Despliega agentes IA autónomos (Whale Watcher, Sniper, Sentiment) para analizar mercados de Kalshi 24/7.",
    step3_title: "EJECUTAR Y GANAR",
    step3_desc: "Los agentes ejecutan trades al instante vía DFlow. Sigue tu PnL y sube en el leaderboard global.",
    step4_title: "GOBERNANZA",
    step4_desc: "Haz stake de tus ganancias para obtener poder de voto en el Neural Council y proponer nuevos mercados.",

    // Bento Grid
    arch_title: "ARQUITECTURA DEL SISTEMA",
    bento1_title: "Inteligencia Swarm Neural",
    bento1_desc: "Red descentralizada de agentes IA especializados sobre ElizaOS. Potenciado por DeepSeek R1 para privacidad local.",
    bento2_title: "Ejecución Instantánea",
    bento2_desc: "Impulsado por la blockchain de alta velocidad de Solana.",
    bento3_title: "Integración Kalshi",
    bento3_desc: "Feed directo de Kalshi, el primer exchange regulado por la CFTC para contratos de eventos.",
    bento4_title: "Liquidez DFlow",
    bento4_desc: "Liquidez agregada vía DFlow que asegura un slippage mínimo mediante ruteo avanzado.",
    bento5_title: "NeuralVault",
    bento1_desc_v2: "Bóveda USDC basada en Anchor. Define límites de riesgo on-chain. Tarifa del 0.5% auto-recaudada.",
    bento6_title: "Integración Jupiter",
    bento6_desc: "Intercambia SOL, USDC o BONK directamente desde la interfaz de ejecución.",
    mpp_title: "PASARELA MPP X402",
    mpp_desc: "Monetización API Machine-to-Machine. Cada predicción cuesta 0.05 USDC mediante HTTP 402.",
    multi_llm_title: "ORQUESTADOR MULTI-LLM",
    multi_llm_desc: "DeepSeek R1 (local) → Claude 3.5 Sonnet (estructura) → OpenAI o1 (validación).",

    // Agents Creation
    agent_genesis: "PROTOCOLO GÉNESIS DE AGENTES",
    select_archetype: "SELECCIONAR ARQUETIPO",
    archetype_desc: "Elige el núcleo de personalidad neural. Define la filosofía de trading del agente.",
    sniper_title: "EL FRANCOTIRADOR",
    sniper_desc: "Alta frecuencia. Ejecuta en micro-divergencias.",
    oracle_title: "EL ORÁCULO",
    oracle_desc: "Análisis de sentimiento. Escanea X y News API.",
    hedger_title: "EL HEDGER",
    hedger_desc: "Delta-neutral. Cosecha recompensas de ejecutor.",
    whale_title: "RASTREADOR DE BALLENAS",
    whale_desc: "Sigue movimientos de wallets grandes. Copia al dinero inteligente.",
    next_phase: "SIGUIENTE FASE",
    back: "ATRÁS",
    system_calibration: "CALIBRACIÓN DEL SISTEMA",
    calibration_desc: "Configura parámetros de riesgo y asignación de capital. Mayor apalancamiento aumenta la volatilidad.",
    risk_tolerance: "TOLERANCIA AL RIESGO",
    capital: "CAPITAL",
    leverage: "APALANCAMIENTO",
    safe: "SEGURO",
    yolo: "YOLO",
    degen: "DEGEN",
    aggressive: "AGRESIVO",
    conservative: "CONSERVADOR",

    // Footer
    footer_desc: "El protocolo Neural Market ofrece liquidez para eventos de grado institucional. Potenciado por el feed directo de la API de Kalshi y asegurado mediante orquestación MPC y CCP para enjambres de agentes de IA autónomos.",
    footer_platform: "PLATAFORMA",
    footer_support: "SOPORTE",
    footer_legal: "LEGAL",
    footer_help: "Centro de Ayuda",
    footer_faq: "Preguntas Frecuentes",
    footer_contact: "Contáctanos",
    footer_terms: "Términos de Servicio",
    footer_privacy: "Privacidad",
    footer_risk: "Aviso de Riesgo",
    footer_status: "ESTADO DEL SISTEMA",
    footer_contract: "CONTRATO",

    // Markets
    markets_title: "LIQUIDEZ INSTITUCIONAL",
    markets_subtitle: "Accede a contratos de eventos institucionales en tiempo real potenciados por la API de Kalshi. Validados por un Swarm Multi-LLM con ejecución on-chain vía NeuralVaults.",
    markets_stat_active: "Mercados Activos",
    markets_stat_vol: "Volumen 24h",
    markets_stat_new: "Nuevas Peticiones",
    markets_propose: "Proponer Nuevo Mercado",
    search_placeholder: "BUSCAR POR TICKER O EVENTO...",
    sort_by: "Ordenar Por",
    sort_vol: "MAYOR VOLUMEN",
    sort_new: "RECIÉN LISTADOS",
    reveal_more: "REVELAR MÁS",
    analyzing: "ANALIZANDO...",
    no_matches: "No se encontraron coincidencias para tus filtros actuales.",
    clear_filters: "LIMPIAR TODOS LOS FILTROS",
    cat_all: "TODOS",
    cat_crypto: "CRIPTO",
    cat_eco: "ECONOMÍA",
    cat_pol: "POLÍTICA",
    cat_sci: "CIENCIA",
    cat_cul: "CULTURA",
    yes: "SÍ",
    no: "NO",
    price: "PRECIO",
    trade: "OPERAR",

    // Leaderboard
    leaderboard_title: "AGENTES IA",
    leaderboard_subtitle: "Agentes autónomos de mayor rendimiento en la red neural. Clasificados por ELO y validados mediante Consenso Cognitivo de 3 niveles.",
    total_agents: "Total Agentes",
    total_tvl: "Volumen Total (TVL)",
    search_agents: "Busca agentes por nombre o ID...",
    syncing: "SINCRONIZANDO CON SOLANA...",
    no_agents: "NO SE ENCONTRARON AGENTES",
    adjust_filters: "Intenta ajustar tus filtros",
    rank: "RANGO",
    score: "PUNTUACIÓN",
    leaderboard_header: "RANKING DE AGENTES",
    leaderboard_desc: "Agentes Neurales con Mejor Rendimiento (Todos)",
    scanning: "ESCANEANDO BLOCKCHAIN POR AGENTES TOP...",
    no_trades: "NO SE HAN ENCONTRADO AGENTES CON TRADES",
    trades: "OPERACIONES",
    win_rate: "WIN RATE",
    total_pnl: "PNL TOTAL",
    showing_top: "Mostrando los mejores 10 de",
    agents_count: "agentes",
    view_details: "VER DETALLES",
    active: "ACTIVO",
    verified: "VERIFICADO",
    lifetime_earnings: "Ganancias Totales",
    managed_assets: "Activos Gestionados",
    total_executions: "Ejecuciones Totales",
    neural_strategy: "ESTRATEGIA NEURAL",
    recent_activity: "ACTIVIDAD RECIENTE",
    neural: "NEURAL",
    simulation_deploy: "SIMULACIÓN Y DESPLIEGUE",
    simulation_desc: "Revisa el rendimiento histórico basado en los parámetros seleccionados. Los resultados pueden variar en mercados en vivo.",
    protocol_license_fee: "Tarifa de Licencia del Protocolo",
    deploy_legal_notice: "Al hacer clic en Desplegar, confirmas que esta es una tarifa de licencia de software no reembolsable para utilizar la infraestructura de NeuralVault. Las comisiones de red (~0.000005 SOL) son aparte.",
    pay_and_deploy: "PAGAR 0.05 SOL Y DESPLEGAR",
    initiating_genesis: "INICIANDO GÉNESIS",
    initializing_neural_link: "INICIALIZANDO ENLACE NEURAL...",
    deploying_agent_status: "DESPLEGANDO AGENTE...",
    required_fee_status: "REQUERIDO: 0.05 SOL TARIFA DE PROTOCOLO",
    requesting_signature_status: "SOLICITANDO FIRMA DE WALLET...",
    waiting_confirmation_status: "ESPERANDO CONFIRMACIÓN...",
    deployed_successfully_status: "AGENTE DESPLEGADO CON ÉXITO ✓",
    connect_wallet_deploy: "POR FAVOR CONECTA TU WALLET PARA DESPLEGAR",
    transaction_cancelled: "TRANSACCIÓN CANCELADA POR EL USUARIO",
    deployment_failed: "DESPLIEGUE FALLIDO",
    view_explorer: "VER EN EXPLORADOR",
    confirm_deactivate: "¿Estás seguro de que deseas desactivar a {name}?",
    connect_wallet_action: "¡Por favor, conecta tu wallet primero!",
    the_agora: "EL AGORA",
    agora_desc: "Gobernanza ponderada por participación facilitada por el {council}. Las propuestas más votadas se envían automáticamente a Kalshi/DFlow para su listado a través de oleoductos descentralizados.",
    neural_council: "Consejo Neural",
    connect_wallet_vote: "Conecta tu wallet para votar propuestas",
    request_market: "SOLICITAR NUEVO MERCADO",
    total_proposals: "PROPUESTAS TOTALES",
    votes_cast_total: "VOTOS EMITIDOS (TOTAL)",
    top_proposal_votes: "VOTOS DE PROPUESTA TOP",
    filter_all: "TODO",
    filter_trending: "TENDENCIA",
    filter_new: "NUEVO",
    filter_ending: "TERMINA PRONTO",
    loading_proposals: "CARGANDO PROPUESTAS...",
    council_access_only: "ACCESO SÓLO AL CONSEJO",
    council_denied_desc: "Enviar nuevas propuestas de gobernanza requiere un NFT de Membresía del Consejo Neural y participación de reputación activa. Por favor, ve al Panel de la DAO para calificar.",
    by_author: "por",
    threshold: "Umbral",
    voted: "VOTADO",
    vote_action: "VOTAR",
    voting: "VOTANDO...",
    vote_failed: "Voto fallido",
    acknowledge: "ENTENDIDO",
    copy_trade: "COPIAR TRADE (PRONTO)",
    view_solana: "VER EN SOLANA",
    strategy_desc_sniper: "utiliza una estrategia SNIPER, enfocándose en entradas de alta frecuencia y salidas rápidas basadas en desequilibrios de flujo de órdenes en DFlow.",
    strategy_desc_whale: "utiliza una estrategia WHALE, enfocándose en acumulación a largo plazo y seguimiento de tendencias a gran escala mediante análisis de volumen on-chain.",
    strategy_desc_default: "utiliza una estrategia equilibrada, enfocándose en la gestión de riesgos y entradas ponderadas por probabilidad en los principales mercados de predicción.",

    // Cortex System
    swarm_intel: "INTELIGENCIA SWARM",
    swarm_desc: "Sistema de Gestión de Enjambre Autónomo v5.0",
    activate_swarm: "ACTIVAR SWARM",
    deactivate_swarm: "DESACTIVAR SWARM",
    deploy_agent: "DESPLEGAR AGENTE",
    live_balance: "BALANCE EN VIVO (DEVNET)",
    connecting: "CONECTANDO...",
    scanning_addr: "ESCANEANDO DIRECCIÓN...",
    vault_performance: "RENDIMIENTO DEL VAULT (ON-CHAIN)",
    accuracy: "PRECISIÓN",
    verified_predictions: "PREDICCIONES VERIFICADAS",
    based_on: "BASADO EN",
    my_agents: "MIS AGENTES DESPLEGADOS",
    manage_swarms: "Gestiona tus enjambres autónomos activos en Solana Devnet",
    no_agents_deployed: "AÚN NO HAY AGENTES DESPLEGADOS",
    create_first: "CREA TU PRIMER AGENTE",
    fetching_logs: "OBTENIENDO REGISTROS ON-CHAIN...",
    no_recent_activity: "NO SE ENCONTRÓ ACTIVIDAD RECIENTE",
    recent_onchain: "ACTIVIDAD RECIENTE ON-CHAIN",
    execute_trade: "Ejecutar Trade",
    manage_liquidity: "Gestionar Liquidez",
    stop_agent: "Detener Agente",
    reactivating: "Reactivando agente...",
    deactivating: "Desactivando agente...",
    agent_deactivated: "¡Agente desactivado!",
    agent_reactivated: "¡Agente reactivado!",
    view_tx: "Ver Transacción",
    trade_action: "TRADE",
    deposit: "DEPOSITAR",
    reactivate: "REACTIVAR AGENTE",
    risk: "RIESGO",
    leverage_short: "APAL.",
    performance: "RENDIMIENTO",
    error: "ERROR",
    active_nodes: "NODOS ACTIVOS (SWARM)",
    status: "ESTADO",
    executing: "EJECUTANDO",
    connecting_hive: "CONECTANDO A LA COLMENA...",
    conf: "CONF",
    neural_core: "NÚCLEO NEURAL",
    processing: "PROCESANDO",
    network_status: "ESTADO DE RED",
    devnet_live: "DEVNET EN VIVO",
    offline: "DESCONECTADO",
    agent_balance_sol: "BALANCE AGENTE (USDC)",
    vault_volume: "VOLUMEN DEL VAULT",
    predictions: "PREDICCIONES",
    live: "EN VIVO",
    system_initializing: "INICIALIZANDO SISTEMA...",
    waiting_feed: "ESPERANDO FEED NEURAL...",
    global_feed: "Feed de Sincronización Global",
    realtime_logs: "Logs de Transacciones en Tiempo Real (Devnet)",
    signature: "Firma",
    slot: "Slot",
    time: "Hora",
    view: "Ver",
    failed: "FALLIDO",
    confirmed: "CONFIRMADO",
    no_activity: "No se detectó actividad on-chain aún",
  },
  zh: {
    // Navbar
    home: "首页",
    markets: "市场",
    ai_agents: "AI 代理",
    swarm_ai: "群集 AI",
    portfolio: "投资组合",
    governance: "治理",
    launch_terminal: "启动终端",
    footer_tx: "最新交易",

    // Hero
    hero_headline: "机构级 AI 预测 · 链上执行",
    hero_subtitle: "多 LLM 群集 (DeepSeek R1 → Claude 3.5 → OpenAI o1) + 非托管 NeuralVaults + 机器支付协议 (x402)。零幻觉。全链审计路径。",
    hero_cta1: "初始化终端",
    hero_cta2: "群集指挥中心",

    // Workflow
    workflow_title: "协议流程",
    workflow_subtitle: "从连接到执行，Neural Market 在一个无信任、自动化的基础设施上运行。",
    step1_title: "连接身份",
    step1_desc: "关联您的 Solana 钱包，在神经网络中建立可验证的链上身份。",
    step2_title: "启动群集",
    step2_desc: "部署自主 AI 代理（巨鲸观察者、狙击手、情感分析）24/7 全天候分析 Kalshi 市场。",
    step3_title: "执行与收益",
    step3_desc: "代理通过 DFlow 立即执行交易。在仪表板上跟踪盈亏，攀升全球排行榜。",
    step4_title: "治理",
    step4_desc: "质押收益以获得神经委员会的投票权，并提议新的预测市场。",

    // Bento Grid
    arch_title: "系统架构",
    bento1_title: "神经群集智能",
    bento1_desc: "运行在 ElizaOS 上的专用 AI 代理去中心化网络。由 DeepSeek R1 驱动实现本地隐私。",
    bento2_title: "即时执行",
    bento2_desc: "由 Solana 高吞吐量区块链驱动。",
    bento3_title: "Kalshi 集成",
    bento3_desc: "来自 Kalshi 的直接数据源，这是首个受 CFTC 监管的事件合约交易所。",
    bento4_title: "DFlow 流动性",
    bento4_desc: "通过 DFlow 聚合流动性，利用高级订单路由确保最小滑点。",
    bento5_title: "NeuralVault",
    bento1_desc_v2: "基于 Anchor 的 Solana USDC 保险库。链上设置风险限制，自动收取 0.5% 许可费。",
    bento6_title: "Jupiter 集集成",
    bento6_desc: "直接在执行界面内无缝兑换 SOL、USDC 或 BONK。",
    mpp_title: "MPP X402 网关",
    mpp_desc: "机器对机器 API 货币化。每次预测调用通过 HTTP 402 强制支付 0.05 USDC。",
    multi_llm_title: "多 LLM 编排器",
    multi_llm_desc: "DeepSeek R1 (本地) → Claude 3.5 Sonnet (结构) → OpenAI o1 (风险验证)。",

    // Agents Creation
    agent_genesis: "代理创世协议",
    select_archetype: "选择原型",
    archetype_desc: "选择神经人格核心。这定义了代理的基本交易哲学。",
    sniper_title: "狙击手",
    sniper_desc: "高频。执行微小分歧交易。",
    oracle_title: "先知",
    oracle_desc: "情感分析。抓取 X & 新闻 API。",
    hedger_title: "对冲者",
    hedger_desc: "Delta 中性。赚取执行者奖励。",
    whale_title: "巨鲸跟踪",
    whale_desc: "跟踪大额钱包动态。跟单聪明钱。",
    next_phase: "下一阶段",
    back: "返回",
    system_calibration: "系统校准",
    calibration_desc: "配置风险参数和资本分配。更高杠杆会增加波动敞口。",
    risk_tolerance: "风险承受能力",
    capital: "资本",
    leverage: "杠杆",
    safe: "安全",
    yolo: "投机",
    degen: "大赌",
    aggressive: "激进",
    conservative: "保守",

    // Footer
    footer_desc: "Neural Market 协议提供机构级事件流动性. 由 Direct Kalshi API Feed 驱动，并通过用于自治 AI 代理群集的分布式 MPC 和 CCP 编排进行保护。",
    footer_platform: "平台",
    footer_support: "支持",
    footer_legal: "法律",
    footer_help: "帮助中心",
    footer_faq: "常见问题",
    footer_contact: "联系我们",
    footer_terms: "服务条款",
    footer_privacy: "隐私政策",
    footer_risk: "风险披露",
    footer_status: "系统状态",
    footer_contract: "合约",

    // Markets
    markets_title: "机构级流动性",
    markets_subtitle: "访问由 Kalshi API 驱动的实时机构事件合约。由三层多 LLM 群集验证，并通过 NeuralVaults 进行全链执行。",
    markets_stat_active: "活跃市场",
    markets_stat_vol: "24h 成交额",
    markets_stat_new: "新请求",
    markets_propose: "提案新市场",
    search_placeholder: "按代码或事件搜索...",
    sort_by: "排序方式",
    sort_vol: "最高成交额",
    sort_new: "最新列出的",
    reveal_more: "显示更多",
    analyzing: "分析中...",
    no_matches: "未找到符合当前过滤条件的匹配项。",
    clear_filters: "清除所有过滤器",
    cat_all: "全部",
    cat_crypto: "加密货币",
    cat_eco: "经济",
    cat_pol: "政治",
    cat_sci: "科学",
    cat_cul: "文化",
    yes: "是",
    no: "否",
    price: "价格",
    trade: "交易",

    // Leaderboard
    leaderboard_title: "AI 代理",
    leaderboard_subtitle: "神经网络中表现最佳的自主代理。按 ELO 评级排序，通过三层认知共识验证 (DeepSeek → Claude → OpenAI)。",
    total_agents: "代理总数",
    total_tvl: "总成交额 (TVL)",
    search_agents: "按名称或 ID 搜索代理...",
    syncing: "正在与 SOLANA 区块链同步...",
    no_agents: "未找到代理",
    adjust_filters: "尝试调整过滤器",
    rank: "排名",
    score: "分数",
    leaderboard_header: "代理排行榜",
    leaderboard_desc: "表现最佳的神经代理（全网）",
    scanning: "正在链上扫描顶级代理...",
    no_trades: "尚未找到有交易记录的代理",
    trades: "交易次数",
    win_rate: "胜率",
    total_pnl: "总盈亏",
    showing_top: "显示前 10 名，共",
    agents_count: "名代理",
    view_details: "查看详情",
    active: "活跃",
    verified: "已验证",
    lifetime_earnings: "累计收益",
    managed_assets: "管理资产",
    total_executions: "执行总数",
    neural_strategy: "神经策略",
    recent_activity: "近期活动",
    neural: "神经",
    simulation_deploy: "模拟与部署",
    simulation_desc: "查看基于所选参数的历史表现。实时市场的结果可能会有所不同。",
    protocol_license_fee: "协议许可费",
    deploy_legal_notice: "点击部署即表示您确认这是使用 NeuralVault 基础设施的不可退还软件许可费。网络费用（约 0.000005 SOL）另计。",
    pay_and_deploy: "支付 0.05 SOL 并部署",
    initiating_genesis: "启动创世协议",
    initializing_neural_link: "正在初始化神经链路...",
    deploying_agent_status: "正在部署代理...",
    required_fee_status: "必需：0.05 SOL 协议费用",
    requesting_signature_status: "正在请求钱包签名...",
    waiting_confirmation_status: "等待确认中...",
    deployed_successfully_status: "代理部署成功 ✓",
    connect_wallet_deploy: "请连接钱包以部署代理",
    transaction_cancelled: "用户取消了交易",
    deployment_failed: "部署失败",
    view_explorer: "在浏览器中查看",
    confirm_deactivate: "您确定要停用 {name} 吗？",
    connect_wallet_action: "请先连接您的钱包！",
    the_agora: "集会场 (AGORA)",
    agora_desc: "由 {council} 促进的股权加权治理。投票最高的提案将通过去中心化管道自动提交给 Kalshi/DFlow 进行上市。",
    neural_council: "神经理事会",
    connect_wallet_vote: "连接钱包以对提案进行投票",
    request_market: "申请新市场",
    total_proposals: "提案总数",
    votes_cast_total: "投票总数 (累计)",
    top_proposal_votes: "最高提案票数",
    filter_all: "全部",
    filter_trending: "热门",
    filter_new: "最新",
    filter_ending: "即将结束",
    loading_proposals: "正在加载提案...",
    council_access_only: "仅限理事会访问",
    council_denied_desc: "提交新的治理提案需要神经理事会会员 NFT 和活跃的声誉质押。请前往 DAO 仪表板以获取资格。",
    by_author: "由",
    threshold: "阈值",
    voted: "已投票",
    vote_action: "投票",
    voting: "投票中...",
    vote_failed: "投票失败",
    acknowledge: "确认 (ACKNOWLEDGE)",
    copy_trade: "跟单交易 (即将推出)",
    view_solana: "在 SOLANA 查看",
    strategy_desc_sniper: "采用 SNIPER 策略，专注于基于 DFlow 订单流失衡的高频入场和快速离场。",
    strategy_desc_whale: "采用 WHALE 策略，专注于长期积累和利用链上成交量分析进行大规模趋势跟踪。",
    strategy_desc_default: "采用平衡策略，专注于主要预测市场的风险管理和概率加权入场。",

    // Cortex System
    swarm_intel: "群集智能",
    swarm_desc: "自主群集 management 系统 v5.0",
    activate_swarm: "激活群集",
    deactivate_swarm: "停用群集",
    deploy_agent: "部署新代理",
    live_balance: "实时钱包余额 (DEVNET)",
    connecting: "连接中...",
    scanning_addr: "正在扫描地址...",
    vault_performance: "保险库表现 (链上)",
    accuracy: "准确率",
    verified_predictions: "已验证预测",
    based_on: "基于",
    my_agents: "我的已部署代理",
    manage_swarms: "在 Solana Devnet 上管理您的活跃自主群集",
    no_agents_deployed: "尚未部署任何代理",
    create_first: "创建您的第一个代理",
    fetching_logs: "正在获取链上日志...",
    no_recent_activity: "未发现近期 activity",
    recent_onchain: "近期链上活动",
    execute_trade: "执行交易",
    manage_liquidity: "管理流动性",
    stop_agent: "停止代理",
    reactivating: "正在重新激活代理...",
    deactivating: "正在停用代理...",
    agent_deactivated: "代理已停用！",
    agent_reactivated: "代理已重新激活！",
    view_tx: "查看交易",
    trade_action: "交易",
    deposit: "存入",
    reactivate: "重新激活代理",
    risk: "风险",
    leverage_short: "杠杆",
    performance: "表现",
    error: "错误",
    active_nodes: "活跃节点 (群集)",
    status: "状态",
    executing: "执行中",
    connecting_hive: "正在连接群集中心...",
    conf: "置信度",
    neural_core: "神经核心",
    processing: "处理中",
    network_status: "网络状态",
    devnet_live: "测试网实时",
    offline: "离线",
    agent_balance_sol: "代理余额 (USDC)",
    vault_volume: "保险库成交额",
    predictions: "预测数",
    live: "实时",
    system_initializing: "系统初始化中...",
    waiting_feed: "等待神经反馈...",
    global_feed: "全球同步反馈",
    realtime_logs: "实时链上交易日志 (测试网)",
    signature: "签名",
    slot: "插槽",
    time: "时间",
    view: "查看",
    failed: "失败",
    confirmed: "已确认",
    no_activity: "尚未检测到链上活动",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");

  // Load locale from localStorage
  useEffect(() => {
    const saved = localStorage.getItem("neural_locale") as Locale;
    if (saved && ["en", "es", "zh"].includes(saved)) {
      setLocale(saved);
    }
  }, []);

  const handleSetLocale = (newLocale: Locale) => {
    setLocale(newLocale);
    localStorage.setItem("neural_locale", newLocale);
  };

  const t = (key: string) => {
    return translations[locale][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
